services:
  db:
    image: postgres:16-alpine
    container_name: tiktoktracker-db
    restart: always
    environment:
      POSTGRES_DB: tiktoktracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: TikTokTracker.Web/Dockerfile
    container_name: tiktoktracker-app
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tiktoktracker;Username=postgres;Password=postgres
    ports:
      - "5000:8080"
    depends_on:
      - db
    volumes:
      - app-keys:/app/keys

  recorder:
    build:
      context: ./recorder-service
      dockerfile: Dockerfile
    container_name: tiktoktracker-recorder
    restart: always
    environment:
      - TIKTOK_SESSION_ID=f400113f39e0ffaf4ef6ab03317aaadb
    ports:
      - "8000:8000"
    volumes:
      - tiktok-recordings:/app/recordings

volumes:
  pgdata:
  app-keys:
  tiktok-recordings:
